
export const leftPre = `
  <pre class="code-logo-left">



                                                   <span class="code-logo-color-3">,<span class="code-logo-color-1">
<span class="code-logo-color-3">yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy$<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
<span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span></span></span></span></span></span></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">0<span class="code-logo-color-1">
<span class="code-logo-color-5"><span class="code-logo-color-2">00</span></b></span></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">1</b></span>
<span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">0<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
</span></span></span></span>
  </pre>
`;

export const rightPre = `
  <pre class="code-logo-right">



                                                   <span class="code-logo-color-3">,<span class="code-logo-color-1">
<span class="code-logo-color-3">yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy$<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
<span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span></span></span></span></span></span></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">0<span class="code-logo-color-1">
<span class="code-logo-color-5"><span class="code-logo-color-2">00</span></b></span></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">1</b></span>
<span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">0<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
</span></span></span></span>
  </pre>
`;





export const leftPreOld = `
  <pre class="code-logo-left">



                                                   <span class="code-logo-color-3">,<span class="code-logo-color-1">
<span class="code-logo-color-3">yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy$<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
<span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span></span></span></span></span></span></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">0<span class="code-logo-color-1">
<span class="code-logo-color-5"><span class="code-logo-color-2">00</span></b></span></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">1</b></span>
<span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">0<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
</span></span></span></span>
  </pre>
`;

s
  < pre class="code-logo-right" >



  <span class="code-logo-color-3">,<span class="code-logo-color-1">
    <span class="code-logo-color-3">yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy$<span class="code-logo-color-1">
      <span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
        <span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span></span></span></span></span></span></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">0<span class="code-logo-color-1">
          <span class="code-logo-color-5"><span class="code-logo-color-2">00</span></b></span></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">11</b></span><span class="code-logo-color-2">0<span class="code-logo-color-5">1</b></span>
  <span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">00<span class="code-logo-color-5">1</b></span><span class="code-logo-color-2">0<span class="code-logo-color-1">
    <span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
    </span></span></span></span>
</pre >
  `;



