export const leftPre = `
  <pre class="code-logo-left">



                                                   <span class="code-logo-color-3">,<span class="code-logo-color-1">
<span class="code-logo-color-3">yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy$<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
<span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span></span></span></span></span></span></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">X<span class="code-logo-color-1">
<span class="code-logo-color-5"><span class="code-logo-color-2">XX</span></b></span></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">X</b></span>
<span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">X<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
</span></span></span></span>
  </pre>
`;

export const rightPre = `
  <pre class="code-logo-right">



                                                   <span class="code-logo-color-3">,<span class="code-logo-color-1">
<span class="code-logo-color-3">yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy$<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
<span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span></span></span></span></span></span></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">X<span class="code-logo-color-1">
<span class="code-logo-color-5"><span class="code-logo-color-2">XX</span></b></span></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">XX</b></span><span class="code-logo-color-2">X<span class="code-logo-color-5">X</b></span>
<span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">XX<span class="code-logo-color-5">X</b></span><span class="code-logo-color-2">X<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
</span></span></span></span>
  </pre>
`;



