export const leftPre = `
  <pre class="code-logo-left">



                                                   <span class="black">,<span class="code-logo-color-1">
<span class="code-logo-color-3">yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy$<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
<span class="black">00<span class="black">1</b></span></span></span></span></span></span></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">0<span class="code-logo-color-1">
<span class="black"><span class="black">00</span></b></span></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">1</b></span>
<span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">0<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
</span></span></span></span>
  </pre>
`;

export const rightPre = `
  <pre class="code-logo-right">



                                                   <span class="black">,<span class="code-logo-color-1">
<span class="code-logo-color-3">yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy$<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
<span class="black">00<span class="black">1</b></span></span></span></span></span></span></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">0<span class="code-logo-color-1">
<span class="black"><span class="black">00</span></b></span></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">11</b></span><span class="black">0<span class="black">1</b></span>
<span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">00<span class="black">1</b></span><span class="black">0<span class="code-logo-color-1">
<span class="code-logo-color-3">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<span class="code-logo-color-1">
</span></span></span></span>
  </pre>
`;



